version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask Application
  web:
    build: .
    container_name: todo_flask
    environment:
      DB_HOST: db
      DB_NAME: todoapp
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      FLASK_ENV: development
      FLASK_DEBUG: "True"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        python -c 'from functions.models import Schema; Schema()' &&
        echo 'Database initialized!' &&
        python app.py
      "

volumes:
  postgres_data:
